In [37]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [38]:
!pip install evidently

Requirement already satisfied: evidently in /usr/local/lib/python3.12/dist-packages (0.7.21)
Requirement already satisfied: certifi>=2024.7.4 in /usr/local/lib/python3.12/dist-packages (from evidently) (2026.6.17)
Requirement already satisfied: cryptography>=43.0.1 in /usr/local/lib/python3.12/dist-packages (from evidently) (49.0.0)
Requirement already satisfied: deprecation>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from evidently) (2.1.0)
Requirement already satisfied: dynaconf>=3.2.4 in /usr/local/lib/python3.12/dist-packages (from evidently) (3.3.2)
Requirement already satisfied: fsspec>=2024.9.0 in /usr/local/lib/python3.12/dist-packages (from evidently) (2025.3.0)
Requirement already satisfied: iterative-telemetry>=0.0.5 in /usr/local/lib/python3.12/dist-packages (from evidently) (0.0.10)
Requirement already satisfied: litestar>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evidently) (2.24.0)
Requirement already satisfied: nltk>=3.6.7 in /usr/local/lib/python3.12/dist-packages (from evidently) (3.9.1)
Requirement already satisfied: numpy>=1.23.0 in /usr/local/lib/python3.12/dist-packages (from evidently) (2.0.2)
Requirement already satisfied: opentelemetry-proto>=1.25.0 in /usr/local/lib/python3.12/dist-packages (from evidently) (1.43.0)
Requirement already satisfied: pandas>=1.3.5 in /usr/local/lib/python3.12/dist-packages (from pandas[parquet]>=1.3.5->evidently) (2.2.2)
Requirement already satisfied: plotly<6,>=5.10.0 in /usr/local/lib/python3.12/dist-packages (from evidently) (5.24.1)
Requirement already satisfied: pydantic>=1.10.16 in /usr/local/lib/python3.12/dist-packages (from evidently) (2.13.4)
Requirement already satisfied: pyyaml>=6.0.1 in /usr/local/lib/python3.12/dist-packages (from evidently) (6.0.3)
Requirement already satisfied: requests>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from evidently) (2.32.4)
Requirement already satisfied: rich>=13 in /usr/local/lib/python3.12/dist-packages (from evidently) (13.9.4)
Requirement already satisfied: scikit-learn>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from evidently) (1.6.1)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from evidently) (1.16.3)
Requirement already satisfied: statsmodels>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from evidently) (0.14.6)
Requirement already satisfied: typer>=0.3 in /usr/local/lib/python3.12/dist-packages (from evidently) (0.25.1)
Requirement already satisfied: typing-inspect>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from evidently) (0.9.0)
Requirement already satisfied: ujson>=5.4.0 in /usr/local/lib/python3.12/dist-packages (from evidently) (5.13.0)
Requirement already satisfied: urllib3>=1.26.19 in /usr/local/lib/python3.12/dist-packages (from evidently) (2.5.0)
Requirement already satisfied: uuid6>=2024.7.10 in /usr/local/lib/python3.12/dist-packages (from evidently) (2025.0.1)
Requirement already satisfied: uvicorn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.22.0->evidently) (0.49.0)
Requirement already satisfied: watchdog>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from evidently) (6.0.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography>=43.0.1->evidently) (2.0.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from deprecation>=2.1.0->evidently) (26.2)
Requirement already satisfied: appdirs in /usr/local/lib/python3.12/dist-packages (from iterative-telemetry>=0.0.5->evidently) (1.4.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from iterative-telemetry>=0.0.5->evidently) (3.29.4)
Requirement already satisfied: distro in /usr/local/lib/python3.12/dist-packages (from iterative-telemetry>=0.0.5->evidently) (1.9.0)
Requirement already satisfied: anyio>=3 in /usr/local/lib/python3.12/dist-packages (from litestar>=2.19.0->evidently) (4.14.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from litestar>=2.19.0->evidently) (8.4.2)
Requirement already satisfied: httpx>=0.22 in /usr/local/lib/python3.12/dist-packages (from litestar>=2.19.0->evidently) (0.28.1)
Requirement already satisfied: litestar-htmx>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from litestar>=2.19.0->evidently) (0.5.0)
Requirement already satisfied: msgspec>=0.18.2 in /usr/local/lib/python3.12/dist-packages (from litestar>=2.19.0->evidently) (0.21.1)
Requirement already satisfied: multidict>=6.0.2 in /usr/local/lib/python3.12/dist-packages (from litestar>=2.19.0->evidently) (6.7.1)
Requirement already satisfied: multipart>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from litestar>=2.19.0->evidently) (1.3.1)
Requirement already satisfied: polyfactory>=2.6.3 in /usr/local/lib/python3.12/dist-packages (from litestar>=2.19.0->evidently) (3.3.0)
Requirement already satisfied: rich-click in /usr/local/lib/python3.12/dist-packages (from litestar>=2.19.0->evidently) (1.9.8)
Requirement already satisfied: sniffio>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from litestar>=2.19.0->evidently) (1.3.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from litestar>=2.19.0->evidently) (4.15.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk>=3.6.7->evidently) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>=3.6.7->evidently) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk>=3.6.7->evidently) (4.67.3)
Requirement already satisfied: protobuf<8.0,>=5.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-proto>=1.25.0->evidently) (5.29.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.5->pandas[parquet]>=1.3.5->evidently) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.5->pandas[parquet]>=1.3.5->evidently) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.5->pandas[parquet]>=1.3.5->evidently) (2026.2)
Requirement already satisfied: pyarrow>=10.0.1 in /usr/local/lib/python3.12/dist-packages (from pandas[parquet]>=1.3.5->evidently) (18.1.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly<6,>=5.10.0->evidently) (9.1.4)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.10.16->evidently) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.10.16->evidently) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.10.16->evidently) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.0->evidently) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.0->evidently) (3.18)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13->evidently) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13->evidently) (2.20.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.1.1->evidently) (3.6.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.14.0->evidently) (1.0.2)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.3->evidently) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.3->evidently) (0.0.4)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from typing-inspect>=0.9.0->evidently) (1.1.0)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn>=0.22.0->uvicorn[standard]>=0.22.0->evidently) (0.16.0)
Requirement already satisfied: httptools>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.22.0->evidently) (0.8.0)
Requirement already satisfied: python-dotenv>=0.13 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.22.0->evidently) (1.2.2)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.22.0->evidently) (0.22.1)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.22.0->evidently) (1.2.0)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.22.0->evidently) (15.0.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography>=43.0.1->evidently) (3.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.22->litestar>=2.19.0->evidently) (1.0.9)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13->evidently) (0.1.2)
Requirement already satisfied: faker>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from polyfactory>=2.6.3->litestar>=2.19.0->evidently) (40.28.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.5->pandas[parquet]>=1.3.5->evidently) (1.17.0)

In [39]:
import numpy as np
import math
import pandas as pd
import glob
import matplotlib.pyplot as plt
import polars as pl
import seaborn as sns
from datetime import datetime
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from dateutil.relativedelta import relativedelta
import xgboost as xgb
from scipy.stats import ks_2samp
from statsmodels.stats.multitest import multipletests

from evidently import Report
from evidently.presets import DataDriftPreset

# Statistical Drift

Statistical drift is when the underlying properties of dataset change and become statistically different then what was seen previously. In practice, a change in statistical properties of a dataset mean that prior assumption and training of a model might no longer hold up when looking at this new dataset, thus retraining will need to happen.

There is 3 main types of drift: Data Drift (Covariate Shift), Concept Drift and Prior Probability Drift(Target Drift)

Data Drift occurs when distribution of the input data changes over time but the underlying relationship between input(X) and output(Y) stays the same

Concept Drift occurs when the task that the model is given itself changes, meaning that the relationship between X and Y changes. Example if model was told to detect spam, but the type of spam changed significantly

Target Shift occurs when distribution of Target changes, but in reality we dont test this in production because we dont know the Target values of an upcoming month, this is what the model is predicting for.

In [40]:
start_train_date = "2025-01-01T00:00:00.000000"


datasetPath = datasetPath = "/content/drive/MyDrive/Colab Notebooks/nyc-taxi-drift-forecasting/data/aggregatedData.csv"
Catcolumns = ['day_factor', 'PULocationID']
df = pl.read_csv(datasetPath)
df = df.with_columns(
    pl.col("tpep_pickup_datetime").str.to_datetime("%Y-%m-%dT%H:%M:%S%.f")
)
df = df.sort("tpep_pickup_datetime")
df.head()

shape: (5, 9)
┌──────────────────┬──────────────┬────────────┬──────┬───┬──────┬───────┬────────────┬────────────┐
│ tpep_pickup_date ┆ PULocationID ┆ trip_count ┆ hour ┆ … ┆ year ┆ month ┆ is_weekend ┆ day_factor │
│ time             ┆ ---          ┆ ---        ┆ ---  ┆   ┆ ---  ┆ ---   ┆ ---        ┆ ---        │
│ ---              ┆ i64          ┆ i64        ┆ i64  ┆   ┆ i64  ┆ i64   ┆ bool       ┆ str        │
│ datetime[μs]     ┆              ┆            ┆      ┆   ┆      ┆       ┆            ┆            │
╞══════════════════╪══════════════╪════════════╪══════╪═══╪══════╪═══════╪════════════╪════════════╡
│ 2025-01-01       ┆ 22           ┆ 3          ┆ 0    ┆ … ┆ 2025 ┆ 1     ┆ false      ┆ Wednesday  │
│ 00:00:00         ┆              ┆            ┆      ┆   ┆      ┆       ┆            ┆            │
│ 2025-01-01       ┆ 40           ┆ 4          ┆ 0    ┆ … ┆ 2025 ┆ 1     ┆ false      ┆ Wednesday  │
│ 00:00:00         ┆              ┆            ┆      ┆   ┆      ┆       ┆            ┆            │
│ 2025-01-01       ┆ 14           ┆ 4          ┆ 0    ┆ … ┆ 2025 ┆ 1     ┆ false      ┆ Wednesday  │
│ 00:00:00         ┆              ┆            ┆      ┆   ┆      ┆       ┆            ┆            │
│ 2025-01-01       ┆ 218          ┆ 3          ┆ 0    ┆ … ┆ 2025 ┆ 1     ┆ false      ┆ Wednesday  │
│ 00:00:00         ┆              ┆            ┆      ┆   ┆      ┆       ┆            ┆            │
│ 2025-01-01       ┆ 129          ┆ 4          ┆ 0    ┆ … ┆ 2025 ┆ 1     ┆ false      ┆ Wednesday  │
│ 00:00:00         ┆              ┆            ┆      ┆   ┆      ┆       ┆            ┆            │
└──────────────────┴──────────────┴────────────┴──────┴───┴──────┴───────┴────────────┴────────────┘

In [41]:
#Hour x Location Interaction Feature

df = df.with_columns(
    (pl.col('PULocationID').cast(str) + '_' + pl.col('hour').cast(str)).alias('loc_hour_key')
)

df = df.sort(['PULocationID', 'tpep_pickup_datetime'])

# 3. Create the 1-hour and 2-hour lag features using window functions globally
df = df.with_columns([
    pl.col('trip_count').shift(1).over('PULocationID').alias('trip_count_lag_1h'),
    pl.col('trip_count').shift(2).over('PULocationID').alias('trip_count_lag_2h')
])

# Drift Analysis

In [42]:
def covariate_shift_detect(df_base, df_test):
  #significance level
  alpha = 0.05

  df_base = df_base.to_pandas()
  df_test = df_test.to_pandas()
  result = []
  com_numeric_col = (df_base.select_dtypes(include = [np.number])
  .columns.intersection(df_test.select_dtypes(include = [np.number]).columns)
  )
  # Explicitly drop target, dates, and ID features
  colIgnore = ['trip_count', 'month', 'year', 'day_of_month', 'PULocationID']

  features = []
  ks_distances = []
  p_values = []
  feature_drifted = []

  # Set a practical distance threshold instead of relying on p-value
  # 0.05 to 0.10 is standard for large-sample drift detection
  DISTANCE_THRESHOLD = 0.05

  for col in com_numeric_col:
      if col not in colIgnore:
          sample1 = df_base[col].dropna()
          sample2 = df_test[col].dropna()

          if len(sample1) == 0 or len(sample2) == 0:
              continue

          # Perform K-S Test
          stat, p = ks_2samp(sample1, sample2)

          features.append(col)
          ks_distances.append(stat)
          p_values.append(p)

          # Flag drift based on distance, NOT p-value
          feature_drifted.append(stat > DISTANCE_THRESHOLD)

  report = pd.DataFrame({
      "Feature": features,
      "K-S Distance (D)": ks_distances,
      "Raw p-value": p_values,
      "Feature Drifted": feature_drifted
  })

  drifted_features_count = report['Feature Drifted'].sum()

  # Guard against division by zero if no valid features remain
  pct_drifted = drifted_features_count / len(features) if features else 0.0

  # Dataset is considered drifted if more than 20% of your operational features genuinely drift
  dataset_drifted = pct_drifted > 0.20

  return {
      "dataset_drifted": dataset_drifted,
      "percentage_features_drifted": round(pct_drifted * 100, 2),
      "feature_report": report
  }

In [43]:
#Concept Drift

def concept_drift_with_warmup(train_res, test_res, delta=0.005, lambda_thresh=50.0):
    # Establish the initial baseline using historical training errors
    abs_train_errors = np.abs(train_res)
    running_mean = np.mean(abs_train_errors)

    # Initialize the sum tracker
    sum_m = 0.0
    min_sum_m = float('inf')

    drift_detected = False
    drift_index = -1

    abs_test_errors = np.abs(test_res)

    # Start checking the test errors with historical context intact
    for t, error in enumerate(abs_test_errors):
        # Update the mean using a continuous sample count
        # (len(train_res) prevents a few early test points from skewing the mean)
        total_samples = len(abs_train_errors) + t + 1
        running_mean = running_mean + (error - running_mean) / total_samples

        # Accumulate the deviations
        sum_m += (error - running_mean - delta)

        if sum_m < min_sum_m:
            min_sum_m = sum_m

        if (sum_m - min_sum_m) > lambda_thresh:
            drift_detected = True
            drift_index = t
            break

    return drift_detected, drift_index

In [44]:


start_train_date = datetime(2025, 1, 1)
end_train_date = datetime(2025, 12, 31)

window_size = 4
forecast_size = 1

results = []
metrics_summary = []
current_train_start = start_train_date



reports = pd.DataFrame(columns = ["BaseMonths","TestMonths","Report" ])

while True:
  current_train_end = current_train_start + relativedelta(months=window_size)
  current_test_end = current_train_end + relativedelta(months=forecast_size)

  if current_test_end > end_train_date:
    break



  train_df = df.filter(
      (pl.col("tpep_pickup_datetime") >= current_train_start) &
      (pl.col("tpep_pickup_datetime") < current_train_end)
  )

  test_df = df.filter(
      (pl.col("tpep_pickup_datetime") >= current_train_end) &
      (pl.col("tpep_pickup_datetime") < current_test_end)
  )



  loc_hour_avg = (
    train_df.group_by('loc_hour_key')
    .agg(pl.col('trip_count').mean().alias('loc_hour_avg'))
  )
  global_avg = train_df['trip_count'].mean()


  train_df = train_df.join(loc_hour_avg, on='loc_hour_key', how='left')
  test_df = test_df.join(loc_hour_avg, on='loc_hour_key', how='left')
  test_df = test_df.with_columns(pl.col('loc_hour_avg').fill_null(global_avg))

  train_df = train_df.with_columns([
    pl.col('trip_count_lag_1h').fill_null(pl.col('loc_hour_avg')),
    pl.col('trip_count_lag_2h').fill_null(pl.col('loc_hour_avg'))
  ])

  test_df = test_df.with_columns([
    pl.col('trip_count_lag_1h').fill_null(pl.col('loc_hour_avg')),
    pl.col('trip_count_lag_2h').fill_null(pl.col('loc_hour_avg'))
  ])


  train_df = train_df.drop(['loc_hour_key'])
  test_df = test_df.drop(['loc_hour_key'])


  #Data Drift

  #Kolmogorov-Smirnov (K-S) Test
  #Null Hypothesis being that the 2 datasets come from the same distribution
  KSTest = covariate_shift_detect(train_df, test_df)

  if KSTest["dataset_drifted"]:
    print(f"There has been a data drift with {KSTest["percentage_features_drifted"]}% of the features thus a covariate shift")
    print("Occured when comparing base months of " + current_train_start.strftime("%B") + "-" + (current_train_end - relativedelta(months=1)).strftime("%B") + " to test month of " + current_train_end.strftime("%B"))
    print(KSTest["feature_report"])

  #Page Hinkley Method
  pHTest = Report([DataDriftPreset()], include_tests= True)
  eval = pHTest.run(current_data = test_df.to_pandas().drop(columns = ['trip_count', 'month', 'year', 'day_of_month','PULocationID']), reference_data = train_df.to_pandas().drop(columns = ['trip_count', 'month', 'year', 'day_of_month', 'PULocationID']))
  newReport = pd.DataFrame([{
    "BaseMonths": current_train_start.strftime("%B") + "-" + (current_train_end - relativedelta(months=1)).strftime("%B"),
    "TestMonths": current_train_end.strftime("%B") ,
    "Report": eval
}])

  reports = pd.concat([reports, newReport], ignore_index = True)


  # Step 2: recombine to one-hot encode consistently, then re-split

  combined = pl.concat([train_df.with_columns(pl.lit('train').alias('_split')),
                       test_df.with_columns(pl.lit('test').alias('_split'))])


  combined = combined.to_dummies(Catcolumns, drop_first=True)

  combined = combined.with_columns([
    (2 * np.pi * pl.col('hour') / 24).sin().alias('hour_sin'),
    (2 * np.pi * pl.col('hour') / 24).cos().alias('hour_cos')
  ])

  test_timestamps = test_df['tpep_pickup_datetime'].to_numpy()


  combined = combined.drop('tpep_pickup_datetime')
  train_df = combined.filter(pl.col('_split') == 'train').drop('_split')
  test_df = combined.filter(pl.col('_split') == 'test').drop('_split')


  train_df = train_df.to_pandas()
  test_df = test_df.to_pandas()

  X_train, y_train = train_df.drop(columns = 'trip_count'), train_df['trip_count']
  X_test, y_test = test_df.drop(columns = 'trip_count'), test_df['trip_count']


  X_train = X_train.drop(columns=['hour'])
  X_test = X_test.drop(columns=['hour'])





  #Using and Testing on Chosen Model of XGBoost


  xgModel = xgb.XGBRegressor(
    tree_method = 'hist',
    enable_categorical = True,
    n_estimators=200,     # Maximum number of sequential trees
    max_depth=6,          # Depth of each tree
    learning_rate=0.02,    # Step size shrinkage (eta)

  )

  xgModel.fit(X_train, y_train,
    eval_set=[(X_test, y_test)],
    verbose=100)

  y_predX = xgModel.predict(X_test)

  train_pred = xgModel.predict(X_train)
  train_resids = y_train - train_pred
  train_mae = mean_absolute_error(y_train, train_pred)

  dynamic_delta = train_mae * 0.2
  dynamic_lambda = train_mae * 500

  res = np.abs(y_predX - y_test)

  #Concept Drift using Page Hinkley on Residuals
  sort_idx = np.argsort(test_timestamps)
  sorted_resids = res.to_numpy()[sort_idx]

  concept_drifted, drifted_at_row = concept_drift_with_warmup(
    train_res=train_resids,
    test_res=sorted_resids,
    delta=dynamic_delta,
    lambda_thresh=dynamic_lambda
)

  if concept_drifted:
    drift_time = test_timestamps[sort_idx][drifted_at_row]
    print(f"⚠️ CONCEPT DRIFT DETECTED in month {current_train_end.strftime('%B')}!")
    print(f"Model relationship failed around timestamp: {drift_time}")
    print(f"Prior to drift, mean error was stable, but cumulative loss exceeded threshold.")
  else:
      print(f"✅ Concept stable for {current_train_end.strftime('%B')}. Model patterns hold.")


  mse = mean_squared_error(y_true = y_test, y_pred = y_predX)
  rmse = np.sqrt(mse)
  mae = mean_absolute_error(y_test, y_predX)
  r2 = r2_score(y_test, y_predX)
  print(f"RMSE: {rmse:.4f}")
  print(f"R² Score: {r2:.4f}")
  print(f"Mean Absolute Residual (Matches MAE): {res.mean():.4f}")
  print(f"Max Absolute Residual Error: {res.max():.4f}")


  window_predictions_df = pl.DataFrame({
      "timestamp": test_timestamps,
      "test_month": current_train_end.strftime("%Y-%m"),
      "actuals": y_test.to_numpy(),
      "predictions": y_predX.astype(np.float64)
  })

  results.append(window_predictions_df)

  metrics_summary.append({
      "test_month": current_train_end.strftime("%Y-%m"),
      "rmse": rmse,
      "mae": mae,
      "r2": r2,
      "max_residual": res.max(),
      "mean_residual": res.mean()
  })

  current_train_start = current_train_start + relativedelta(months=1)


forecast_df = pl.concat(results)
forecast_df = forecast_df.with_columns(
    (pl.col("actuals") - pl.col("predictions")).alias("residual")
)

summary_df = pl.DataFrame(metrics_summary)
print("--- RAW PREDICTIONS FRAME (thousands of rows) ---")
print(forecast_df.head())

print(summary_df)

There has been a data drift with 25.0% of the features thus a covariate shift
Occured when comparing base months of January-April to test month of May
             Feature  K-S Distance (D)    Raw p-value  Feature Drifted
0               hour          0.011480   7.027617e-12            False
1  trip_count_lag_1h          0.041985  1.202003e-153            False
2  trip_count_lag_2h          0.041842  1.330202e-152            False
3       loc_hour_avg          0.057061  1.586080e-283             True
[0]	validation_0-rmse:75.46053
[100]	validation_0-rmse:20.41724
[199]	validation_0-rmse:15.87421
⚠️ CONCEPT DRIFT DETECTED in month May!
Model relationship failed around timestamp: 2025-05-01T21:00:00.000000
Prior to drift, mean error was stable, but cumulative loss exceeded threshold.
RMSE: 15.8742
R² Score: 0.9573
Mean Absolute Residual (Matches MAE): 6.5914
Max Absolute Residual Error: 403.2253
[0]	validation_0-rmse:72.09410
[100]	validation_0-rmse:17.87175
[199]	validation_0-rmse:14.08181
⚠️ CONCEPT DRIFT DETECTED in month June!
Model relationship failed around timestamp: 2025-06-05T23:00:00.000000
Prior to drift, mean error was stable, but cumulative loss exceeded threshold.
RMSE: 14.0818
R² Score: 0.9633
Mean Absolute Residual (Matches MAE): 6.1145
Max Absolute Residual Error: 322.3639
[0]	validation_0-rmse:64.51626
[100]	validation_0-rmse:15.38539
[199]	validation_0-rmse:13.71196
⚠️ CONCEPT DRIFT DETECTED in month July!
Model relationship failed around timestamp: 2025-07-01T22:00:00.000000
Prior to drift, mean error was stable, but cumulative loss exceeded threshold.
RMSE: 13.7120
R² Score: 0.9564
Mean Absolute Residual (Matches MAE): 5.9355
Max Absolute Residual Error: 348.8253
[0]	validation_0-rmse:58.70451
[100]	validation_0-rmse:14.20785
[199]	validation_0-rmse:12.79821
⚠️ CONCEPT DRIFT DETECTED in month August!
Model relationship failed around timestamp: 2025-08-13T19:00:00.000000
Prior to drift, mean error was stable, but cumulative loss exceeded threshold.
RMSE: 12.7982
R² Score: 0.9540
Mean Absolute Residual (Matches MAE): 5.5552
Max Absolute Residual Error: 288.5889
[0]	validation_0-rmse:74.06381
[100]	validation_0-rmse:20.03477
[199]	validation_0-rmse:16.49611
⚠️ CONCEPT DRIFT DETECTED in month September!
Model relationship failed around timestamp: 2025-09-04T19:00:00.000000
Prior to drift, mean error was stable, but cumulative loss exceeded threshold.
RMSE: 16.4961
R² Score: 0.9521
Mean Absolute Residual (Matches MAE): 6.8693
Max Absolute Residual Error: 367.1234
[0]	validation_0-rmse:77.08206
[100]	validation_0-rmse:20.50620
[199]	validation_0-rmse:15.62618
⚠️ CONCEPT DRIFT DETECTED in month October!
Model relationship failed around timestamp: 2025-10-03T23:00:00.000000
Prior to drift, mean error was stable, but cumulative loss exceeded threshold.
RMSE: 15.6262
R² Score: 0.9603
Mean Absolute Residual (Matches MAE): 6.5253
Max Absolute Residual Error: 385.9440
[0]	validation_0-rmse:73.95735
[100]	validation_0-rmse:19.67439
[199]	validation_0-rmse:15.75895
⚠️ CONCEPT DRIFT DETECTED in month November!
Model relationship failed around timestamp: 2025-11-01T01:00:00.000000
Prior to drift, mean error was stable, but cumulative loss exceeded threshold.
RMSE: 15.7589
R² Score: 0.9562
Mean Absolute Residual (Matches MAE): 6.5281
Max Absolute Residual Error: 534.8767
--- RAW PREDICTIONS FRAME (thousands of rows) ---
shape: (5, 5)
┌─────────────────────┬────────────┬─────────┬─────────────┬───────────┐
│ timestamp           ┆ test_month ┆ actuals ┆ predictions ┆ residual  │
│ ---                 ┆ ---        ┆ ---     ┆ ---         ┆ ---       │
│ datetime[μs]        ┆ str        ┆ i64     ┆ f64         ┆ f64       │
╞═════════════════════╪════════════╪═════════╪═════════════╪═══════════╡
│ 2025-05-01 05:00:00 ┆ 2025-05    ┆ 1       ┆ 2.530701    ┆ -1.530701 │
│ 2025-05-01 10:00:00 ┆ 2025-05    ┆ 1       ┆ 2.2046      ┆ -1.2046   │
│ 2025-05-01 11:00:00 ┆ 2025-05    ┆ 1       ┆ 2.158829    ┆ -1.158829 │
│ 2025-05-01 12:00:00 ┆ 2025-05    ┆ 2       ┆ 2.183543    ┆ -0.183543 │
│ 2025-05-01 13:00:00 ┆ 2025-05    ┆ 4       ┆ 2.324972    ┆ 1.675028  │
└─────────────────────┴────────────┴─────────┴─────────────┴───────────┘
shape: (7, 6)
┌────────────┬───────────┬──────────┬──────────┬──────────────┬───────────────┐
│ test_month ┆ rmse      ┆ mae      ┆ r2       ┆ max_residual ┆ mean_residual │
│ ---        ┆ ---       ┆ ---      ┆ ---      ┆ ---          ┆ ---           │
│ str        ┆ f64       ┆ f64      ┆ f64      ┆ f64          ┆ f64           │
╞════════════╪═══════════╪══════════╪══════════╪══════════════╪═══════════════╡
│ 2025-05    ┆ 15.874209 ┆ 6.59139  ┆ 0.957336 ┆ 403.225342   ┆ 6.59139       │
│ 2025-06    ┆ 14.081812 ┆ 6.114534 ┆ 0.963273 ┆ 322.363922   ┆ 6.114535      │
│ 2025-07    ┆ 13.711962 ┆ 5.935538 ┆ 0.956422 ┆ 348.825348   ┆ 5.935538      │
│ 2025-08    ┆ 12.798207 ┆ 5.555207 ┆ 0.954022 ┆ 288.588913   ┆ 5.555207      │
│ 2025-09    ┆ 16.496106 ┆ 6.86932  ┆ 0.952108 ┆ 367.123413   ┆ 6.869321      │
│ 2025-10    ┆ 15.62618  ┆ 6.525328 ┆ 0.960268 ┆ 385.943954   ┆ 6.525327      │
│ 2025-11    ┆ 15.758947 ┆ 6.528121 ┆ 0.956217 ┆ 534.876709   ┆ 6.52812       │
└────────────┴───────────┴──────────┴──────────┴──────────────┴───────────────┘

In [45]:
reports.iloc[4]

BaseMonths                                           May-August
TestMonths                                            September
Report        <evidently.core.report.Snapshot object at 0x7a...
Name: 4, dtype: object

In [46]:
reports.iloc[4]["Report"]

Output hidden; open in https://colab.research.google.com to view.